# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39f47dded30658f082687eee42b77436d74938b10d5041a5e09b68f8caaec5d4dd9483c5cf8626f2a1edb85e5c0ff94feda2827b7762fa78459be5853f1fed21

test:
  secret_key_base: 56f4c3cca8a4d711035483e493c5250aea4da1dcf274d4fc427ba6ecd6652762b6098ab901d8fccd3cd640e3cf4c641aba3730c2807121c05322d18096ad95cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
